import type { Metadata } from 'next';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Menu from '@/components/menu';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Huurscout',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('font-sans antialiased', inter.className)}>
        <div className="container max-w-md">
          <div className="flex bg-[#1A1A1A] max-w-sm m-auto p-2 justify-between items-center">
            <h3 className="text-white">
              <Link href="/">
                <Image width={126} height={14} src="/logo.png" alt="logo" />
              </Link>
            </h3>
            <Menu />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
